#!/usr/bin/env python3
"""Build js/mapdata.js (simplified prefecture SVG paths) from a Japan prefecture GeoJSON.

Usage: python3 tools/build_map.py japan.geojson js/mapdata.js
Source used: https://github.com/dataofjapan/land (japan.geojson)
"""
import json, math, sys

SCALE = 60.0                      # SVG units per degree of latitude
LON0, LAT0 = 120.0, 46.0          # top-left origin of the map
KX = math.cos(math.radians(37.0)) # squash longitude so the shape looks right
TOL = 0.55                        # Douglas-Peucker tolerance (SVG units)
MIN_AREA = 7.0                    # drop islands smaller than this (SVG units^2)
OKI_DLON, OKI_DLAT = -2.6, 8.4    # shift Okinawa into an inset box


def is_okinawa(lat, lon):
    return lat < 28.5 and lon < 130


def project(lon, lat, shift=False):
    if shift:
        lon += OKI_DLON
        lat += OKI_DLAT
    return ((lon - LON0) * KX * SCALE, (LAT0 - lat) * SCALE)


def dp(pts, tol):
    if len(pts) < 3:
        return pts
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        ax, ay = pts[a]; bx, by = pts[b]
        dx, dy = bx - ax, by - ay
        L = math.hypot(dx, dy)
        best, idx = -1, -1
        for i in range(a + 1, b):
            px, py = pts[i]
            d = (math.hypot(px - ax, py - ay) if L == 0
                 else abs(dy * (px - ax) - dx * (py - ay)) / L)
            if d > best:
                best, idx = d, i
        if best > tol:
            keep[idx] = True
            stack += [(a, idx), (idx, b)]
    return [p for p, k in zip(pts, keep) if k]


def area(ring):
    s = 0
    for i in range(len(ring)):
        x1, y1 = ring[i]; x2, y2 = ring[(i + 1) % len(ring)]
        s += x1 * y2 - x2 * y1
    return s / 2


def centroid(ring):
    a = area(ring)
    cx = cy = 0
    for i in range(len(ring)):
        x1, y1 = ring[i]; x2, y2 = ring[(i + 1) % len(ring)]
        f = x1 * y2 - x2 * y1
        cx += (x1 + x2) * f; cy += (y1 + y2) * f
    return cx / (6 * a), cy / (6 * a)


def main(src, dst):
    gj = json.load(open(src, encoding="utf-8"))
    prefs, allpts = [], []
    for f in gj["features"]:
        pid = f["properties"]["id"]
        g = f["geometry"]
        polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
        shift = pid == 47
        polys_out = []
        for poly in polys:
            rings = []
            for ring in poly:
                pts = [project(x, y, shift) for x, y in ring]
                if pts[0] == pts[-1]:
                    pts = pts[:-1]
                rings.append(pts)
            polys_out.append(rings)
        polys_out.sort(key=lambda r: -abs(area(r[0])))
        d, main_c = [], None
        for i, rings in enumerate(polys_out):
            if i > 0 and abs(area(rings[0])) < MIN_AREA:
                continue
            for j, ring in enumerate(rings):
                if j > 0 and abs(area(ring)) < MIN_AREA:
                    continue
                s = dp(ring + [ring[0]], TOL)[:-1]
                if len(s) < 3:
                    continue
                allpts += s
                d.append("M" + "L".join(f"{x:.1f},{y:.1f}" for x, y in s) + "Z")
                if i == 0 and j == 0:
                    main_c = centroid(s)
        prefs.append({"id": pid, "d": "".join(d),
                      "cx": round(main_c[0], 1), "cy": round(main_c[1], 1)})
    prefs.sort(key=lambda p: p["id"])
    xs = [p[0] for p in allpts]; ys = [p[1] for p in allpts]
    pad = 14
    vb = [round(min(xs) - pad), round(min(ys) - pad),
          round(max(xs) - min(xs) + 2 * pad), round(max(ys) - min(ys) + 2 * pad)]
    # Okinawa inset frame
    ok = [p for pr in gj["features"] if pr["properties"]["id"] == 47 for p in [pr]][0]
    ox = [project(x, y, True) for poly in ok["geometry"]["coordinates"] for r in poly for x, y in r]
    obox = [round(min(p[0] for p in ox) - 10), round(min(p[1] for p in ox) - 10),
            round(max(p[0] for p in ox) - min(p[0] for p in ox) + 20),
            round(max(p[1] for p in ox) - min(p[1] for p in ox) + 20)]
    data = {"viewBox": vb, "okinawaBox": obox,
            "proj": {"scale": SCALE, "lon0": LON0, "lat0": LAT0, "kx": KX,
                     "okiDLon": OKI_DLON, "okiDLat": OKI_DLAT},
            "prefectures": prefs}
    with open(dst, "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/build_map.py - do not edit by hand.\n")
        fh.write("window.MAP_DATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print("viewBox", vb, "okinawaBox", obox)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
